### ISSUE TITLE
Worker Performance

### ISSUE THREAD

**Issue by PeterBooker** [wptide/sync-server#13]
I believe the delay between plugin/theme svn.wordpress.org changes and Tide tests could potentially be significantly reduced.

From my understanding of the source it can take quite a while for the workers to complete their cycle through all of the plugins/themes using the API. Taking roughly 30mins to traverse through all the plugins alone *(50k plugins, 250 per page, 10 secs delay)*. This means that it could potentially be over 30mins between a plugin being updated and it being added to the SQS queue for testing.

Another strategy would be to use the SVN changelog (only changes since a specific revision) to identify any updated themes/plugins. This is accessible via SVN CLI and/or HTTP API. By polling one of these endpoints constantly (every 5/15/30 seconds?), and sending any plugins/themes listed to the queue, you could reduce the delay between updates and testing to well under a minute.

The only problem I can see is that currently you add the `plugin.Name` and `plugin.ShortDescription` details to the queue, which are not available through the SVN changelog. This would require either not sending them, or requesting the information separately, which may undo any gains.

*Notes: Examples of the changelogs via SVN CLI and HTTP API I mentioned above:*
SVN: `svn log -v -q https://plugins.svn.wordpress.org/ -r 1800041:1800067`
API: `https://plugins.trac.wordpress.org/log/?format=changelog&rev=1800041&limit=400`

**Comment by rheinardkorf** [comment]
@PeterBooker thanks for the heads up on those integration endpoints.

The SyncServer traverses all the plugins rather quickly. Certainly not 30 minutes. The worker pools run several concurrent requests and populate SQS very quickly.  

That said, the primary delay is the timeout before a pool polls everything again. Once all the plugins (or themes) have been processed it will be delayed according to a set environment variable. This is the biggest delay.

If we could indeed check for changes more frequently then yes, we'll be able to remove the overall delay.  The architecture will have to change, because it could potentially eliminate the need for the worker pools (or at least alter their current function).

**Comment by PeterBooker** [comment]
Thank you for the response, I see now that I had misunderstood when the `SYNC_SERVER_DELAY` was applied, and that it is only between polling the repo and not each page. This makes the entire thing much faster.

It seems like the current setup might take, at worst, about a minute to add a change to the queue (depending on how the API endpoint is cached, assuming it is cached). I can see how that would be more than acceptable.

I will have a play around with code to see if I think any significant gains could be made, thank you for helping me to understand how it currently works.

*[Note: As you can see from the slurper, I have been doing similar work. I am currently exploring more similar to Tide, by making a web service slurper so that anyone can search the plugin/theme repos easily. So I have a keen interest in Tide.]*

**Comment by PeterBooker** [comment]
I have some thoughts and queries after spending some time considering sync-server performance (I left a message in Slack in case anyone was around to bounce thoughts around with).

It seems like `audit-server` is the most resource intensive part of the whole system, is that correct?

Working on that assumption I think `sync-server` accuracy, only adding themes/plugins to the SQS queue when they definitely need testing, is potentially important than how fast it identifies changes.

There are several obvious cases where plugin/theme updates do not result in a need for Tide tests. The easiest example is plugins- updates to the root `/assets/` and/or `/branches/` folders. There are more complex cases, updates to `/tags/` or `/trunk/` may or may not need Tide tests, depending on if the stable version is set in the `/trunk/readme.txt`. You can see information about how the readme is used to decide which code to create the .zip with [here](https://developer.wordpress.org/plugins/wordpress-org/how-your-readme-txt-works/).

This leads to another problem, is the contents of the `https://downloads.wordpress.org/plugin/slug.zip` the code we need to test? I asked in #plugins on Slack (thanks Ipstenu/Otto42) and it can take up to an hour for the .zip to update, which means that it might not be reliable/fast enough for Tide. The only alternative I am aware of (thanks to Ipstenu/Otto) is manually doing an `svn export` and using `/trunk/readme.txt` to work out where the code which needs testing (which is how wp.org does it). This is slightly more effort, but reliable.

From the above it seems to me that there are two main challenges before running Tide tests:
* Pickup when changes relevant to Tide have been made (e.g. not just a plugin banner added to /assets/).
* Identify and obtain the files that need to be tested (.e.g whether they are in /tags/1.2/ or /trunk/).

I believe these could both be appropriately handled by sync-server, but it would require parsing the `readme.txt` for each plugin, to calculate the folder which `audit-server` needs to `svn export` for testing (so a change to audit-server too).

I just wanted to drop this here for discussion, as it has become more complex than I expected (and potentially larger than just sync-server).

(note: I have left themes out of the above as I have much less working knowledge. I know their SVN setup is slightly different but I imagine most of the above is true for themes too.)

**Comment by PeterBooker** [comment]
I want to add a follow up before the meeting tonight, I have made a [Gist](https://gist.github.com/PeterBooker/cfd3709447ac590b34672ced422f9934) with a summary of my research into the WP Repositories (only plugins currently).

One thing which stands out is the average of 0.4 plugin updates per minute. This was much lower than I expected and, although spikes need to be considered, I imagine this reduces the importance of performance somewhat.

There are two cases where I believe there are strong arguments for changes to be made:

* The current reliance on the WP org provided .zip archives makes the system fragile, due to a potential 1 hour delay to the archives being updated (worst case, uncommon).

Thoughts: Using the same method as the WP Org site, the `svn export` command, seems like a better choice, but would require changes to `audit-server` too. The benefit of avoiding the potential for an hour delay, or mistakenly testing the wrong files, seems worth it.

* The use of the `https://api.wordpress.org/plugins/info/1.1/` endpoint to fetch a list of updated plugins could be improved. It requires a relatively complex setup involving a large number of HTTP requests (approx 200) and a db storing the latest version number of each plugin.

Thoughts: Like above, replicating the WP Org site, the SVN client commands require less complexity and are faster to process (less requests). In essence, repeatedly polling for the latest revision allows us to tell when an update has occurred. We can then ask for the changelog between our current revision and the new latest revision, giving us only the plugins which have changed. I have a basic working copy of this [here](https://github.com/PeterBooker/wpdirectory/blob/master/sync/plugins.go#L13).

If you believe any of the above is wrong, or have any questions, I would love to hear.
